config:
  versions: 'updatecli/values.d/versions.yaml'

scm:
  user: 'github-actions[bot]'
  email: '41898282+github-actions[bot]@users.noreply.github.com'
  username: 'UPDATECLI_GITHUB_ACTOR'
  token: 'UPDATECLI_GITHUB_TOKEN'
  owner: 'rancher'
  repo: 'rancher'
  branch: 'main'
  # This option allows for the commits to be signed (verified). However, the
  # GraphQL API doesn't allow the commits to be squashed. For the moment we
  # prefer to squash them in order to reduce the noise given the amount of
  # commits that are done for the updates.
  commitusingapi: false
  commitmessage:
    squash: true
  mergemethod: 'squash'

repos:
  harvester_docker_machine:
    owner: 'harvester'
    repo: 'docker-machine-driver-harvester'
  k3s:
    owner: 'k3s-io'
    repo: 'k3s'
  k8s:
    owner: 'kubernetes'
    repo: 'kubernetes'
  system_agent:
    owner: 'rancher'
    repo: 'system-agent'
  wins:
    owner: 'rancher'
    repo: 'wins'

harvester_docker_machine:
  manifest: 'Update Harvester Docker machine driver version'
  pipelineid: 'update-harvester-docker-machine-version'
  commitmessage:
    type: 'deps'
    scope: 'harvester-docker-machine'

k8s_k3s:
  manifest: 'Update K8s and K3s patch versions'
  pipelineid: 'update-k8s-k3s-versions'
  commitmessage:
    type: 'deps'
    scope: 'k8s and k3s'

wins_system_agent:
  manifest: 'Update Wins and System Agent patch versions'
  pipelineid: 'update-wins-system-agent-version'
  commitmessage:
    type: 'deps'
    scope: 'wins and system-agent'
