apiVersion: v2
name: rancher
description: Install Rancher Server to manage Kubernetes clusters across providers.
version: %VERSION%
appVersion: %APP_VERSION%
kubeVersion: < 1.36.0-0
home: https://rancher.com
icon: https://raw.githubusercontent.com/rancher/ui/master/public/assets/images/logos/welcome-cow.svg
keywords:
  - rancher
sources:
  - https://github.com/rancher/rancher
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
