apiVersion: v2
name: rancher
description: Install Rancher Server to manage Kubernetes clusters across providers.
version: %VERSION%
appVersion: %APP_VERSION%
kubeVersion: < 1.30.0-0
home: https://rancher.com
icon: https://github.com/rancher/ui/blob/master/public/assets/images/logos/welcome-cow.svg
keywords:
  - rancher
sources:
  - https://github.com/rancher/rancher
  - https://github.com/rancher/server-chart
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
