apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
{{- if .Values.ingress.configurationSnippet }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- template "configurationSnippet" . }}
{{- end }}
{{- if eq .Values.tls "external" }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # turn off ssl redirect for external.
{{- else }}
  {{- if ne .Values.ingress.tls.source "secret" }}
    {{- if .Capabilities.APIVersions.Has "cert-manager.io/v1alpha2" }}
    cert-manager.io/issuer: {{ template "rancher.fullname" . }}
    {{- else if .Capabilities.APIVersions.Has "certmanager.k8s.io/v1alpha1" }}
    certmanager.k8s.io/issuer: {{ template "rancher.fullname" . }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.hostname }}  # hostname to access rancher server
    http:
      paths:
      - backend:
          serviceName: {{ template "rancher.fullname" . }}
          servicePort: 80
{{- if eq .Values.tls "ingress" }}
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: tls-rancher-ingress
{{- end }}
