kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "rancher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
