{{- if eq (include "rancher.ingressEnabled" .) "true" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
{{ include "rancher.labels" . | indent 4 }}
  annotations:
{{- if .Values.ingress.configurationSnippet }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- template "configurationSnippet" . }}
{{- end }}
{{- if eq (include "rancher.useExternalTls" .) "true" }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # turn off ssl redirect for external.
{{- else }}
  {{- if ne .Values.ingress.tls.source "secret" }}
    cert-manager.io/issuer: {{ template "rancher.fullname" . }}
    cert-manager.io/issuer-kind: Issuer
  {{- end }}
{{- end }}
{{- if .Values.ingress.includeDefaultExtraAnnotations }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
{{- end }}
{{- if eq (int .Values.ingress.servicePort) 443 }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
{{- end }}
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
  rules:
  - host: {{ .Values.hostname }}  # hostname to access rancher server
    http:
      paths:
      - backend:
          {{- if or (.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") (not (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress")) }}
          service:
            name: {{ template "rancher.fullname" . }}
            port:
              number: {{ .Values.ingress.servicePort }}
          {{- else }}
          serviceName: {{ template "rancher.fullname" . }}
          servicePort: {{ .Values.ingress.servicePort }}
          {{- end }}
        {{- if or (.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") (not (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress")) }}
        pathType: {{ .Values.ingress.pathType }}
        path: {{ .Values.ingress.path }}
        {{- end }}
{{- if eq (include "rancher.useExternalTls" .) "false" }}
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
{{- end }}
