name: Validate
on: [pull_request, push]
jobs:
  validate:
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    container: registry.suse.com/bci/python:3.11
    env:
      GOLANG_CI_LINT_VERSION: v2.7.1
      GOLANG_VERSION: '1.25'
    steps:
      - name: Install dependencies
        shell: bash
        run: zypper install -y git awk
      - name: Git safe directory
        run: git config --global --add safe.directory "$PWD"
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Check Python version
        run: |
          python3 --version
          python3 -m ensurepip --upgrade
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: Install Python and dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install tox flake8
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: ${{ env.GOLANG_CI_LINT_VERSION }}
          install-only: true
      - name: Validate
        run: ./scripts/validate
